C_LİST=[
	
"İstədiyiniz sosial media hesabında çox çirkin bir şəklinizi paylaşın.", "Telefonunuzda mesaj bölməsini açın, gözlərinizi yumun və təsadüfi bir adama kor -koranə bir mesaj göndərin.",
 "Növbəti 5 dəqiqə ərzində dediklərinizin hamısından sonra" mee "deyəcəksiniz",
 "Önümüzdəki 5 dəqiqədə kiminsə ev heyvanı olun.", "İnstagramınızı oyunçulardan birinə verin. 5 dəqiqə hər yerə baxmaq üçün sərbəst olun.",
 "Oyundan bir insana serenad edin (oğlan qız olarsa, qız oğlan olarsa)", "Növbəti 3 növbədə ləhcə danışın.",
 "3 dəqiqə körpə kimi davran!" "," Telefonuna ən sevdiyin şəkli göndər "," Sevdiyin şəkli göndər ",
 "Whatsappdakı 2 söhbətinizi ləğv edin", "Şəxsi mesajlarınızı alın və qrupa göndərin", "Whatsappdakı son söhbətinizi ləğv edin",
 "20 dəfə bir dəftərə çatlandığımı yazın və şəklinizi yerləşdirin", "Son çıxışınızı Telegramda bağırın.", "Tərcümeyi -halınıza +18 cümlə yazın; 3 saat dayanacaq!",
 "Qalereyanızın sss hissəsi", "Qalereyanızdakı 16 -cı fotoşəkili atın.", "İnstagram və ya teleqramda tanımadığınız birisinə gülməli bir zarafat söyləyin.",
 "Yüksək Lullaby oxu", "Bu gün haqqında qısa bir hekayə hazırla", "Qrupda ən çox bəyəndiyin əks cinsə mesaj yaz",
 "Qalereyanızdakı 16 -cı fotonu atın.", "Qalereyanızdakı 30 -cu fotonu atın.",
 "Qrupun üzv siyahısına daxil olun və dərhal 7 -ci şəxsə göndərin. (Qrupda daha az adam varsa və ya daha az aktiv nömrə varsa saymağa davam edin)",
 "Ən son danışdığınız şəxsə" Cümə gününüz mübarək olsun "(platformanın əhəmiyyəti yoxdur) yazın",
 "Hazırkı şəxsiyyətinizin şəklini çəkə bilərsinizmi?", "Qrupun üzvlər bölməsinə gedin və 11 -ci şəxsə" Analar nə doğur "deyə qışqırın və cavabınızı qrupla paylaşın.",
 "Profil şəklinizə nifrət etdiyiniz bir məşhurun ​​şəklini qoyun.", Başınıza yumurta vurun və şəklini yerləşdirin ",
 "Qrupda bəyəndiyiniz birinin şəklini profil şəkli olaraq çəkin", "Balkona və ya pəncərəyə çıxın və kənardan gələnlərin eşitməsi üçün mahnı oxuyun və qrupa videoya çəkin.",
 "İtiraf et: üzvlərin oğurlanması üçün neçə hesabın var?", "Qrupdakı 5 fanata" səni sevirəm "de", "iki dəqiqə toyuq kimi davran.", "İstədiyin bir heyvanı təqlid et". ,
 "İstədiyiniz bir obyekti yalayın və şəklini qrupa çəkin.", "Qrupa həqiqətən utanc verici bir şəkil göstərin.",
 "Çirkin bir selfie çəkin və sosial media tətbiqlərindən birində yayımlayın və 1,5 saat qalacaq.", "Bir qaşıq un yeyin və video çəkin və qrupa atın",
 "Tanımadığın birinə Qurban bayramını təbrik et", "Sevdiyin birinə" "Niyə səni sevdim, səni niyə sevdim, bunun izahı yoxdur, görürsən, bəyəndim.  Yaw, "səni niyə sevdim" deyin. Cavab gələndə qrupla paylaşın və güləcəyik ",
 "Telegramda ən böyük qrupu açın və \" Adım turşu qabıdır! \ "Deyərək bir səs yazın və ən böyük qrupa göndərin.", "Yaxın bir dostunuza ona aşiq olduğunuzu söyləyin. "," Küpədən su iç və şəkil çək "
 "Ən çox danışdığınız əks cins dostunuza" Səni çox sevirəm, aşiq olduğumu düşünürəm "yazın və reaksiyanızı bizimlə bölüşün",
 "Adınızı Abdul <adınız> 1 saat edin. (Məsələn, adınız Berkdirsə, AbdulBerk edin)", "İnstagramdakı dm qutunuzu (mesajlar bölməsini) ss qrupuna göndərin.",
 "Bu cümlə ilə tanımadığınız biri ilə söhbətə başlayın: \" Sevgimizin suya düşəcəyini bilsəydim, balıq olardım \ "",
 "Ən gülməli şəklini qrupla paylaş"
 "Bu mesajı tanımadığınız birinə göndərin, sonra cavabınızı qrupla paylaşın ➡️ \ n \" `Bu mesaj xüsusi bir tezliklə göndərildi.  Ağıllı insanlarda yaddaş itkisi, axmaq insanlarda qısa müddətli korluq da bayraqları bir anlıq gülümsəyir! "\" ",
 "@Summer yazan və səni sevirəm yazan ilk şəxsi tag et.",
 "Telegram Haqqında" 1 saat ərzində \ "Babanın Şahzadəsi \" ni yazın.
 "Telegramdakı son söhbətinizi yazın.", 🎀 UĞURLU MESAJ 🎊 Qrupdakı hər kəsin Google/Youtube/Instagram Axtarış Tarixçəsini istəyin ",
 "Qalereyanın 7 -ci şəklini aşağıdan göndərin",
 "Növbəti 3 dönüş üçün ləhcə ilə danışın. Fərqli ləhcələrə girsəniz, /zar əmrindən istifadə edərək 6 -ya ən yaxın gələn oyunçu sizi cəzalandıracaq",
 "Üç xörək qaşığı isti tomat pastası yeyin (və ya buna bənzər) və video çəkin və ya qrupa atın",
 "Oyundakı birindən 5 dəqiqə ərzində ev heyvanı olmasını istəyə bilərsiniz.", "Zəmini yalayın və şəklinizi/videonuzu qrupa göndərin",
 " /Dice əmrindən istifadə edərək, 6 -ya ən yaxın olan oyunçuya sosial media hesablarından birinə 5 dəqiqə verin",
 "Məşhur bir insanı 3 dəqiqə təqlid edin.", "Kimsə təqlid edilən sənətçini təxmin etməyincə bir sənətçini təqlid edin",
 "Qrupun hazırladığı bir mövzu ətrafında səkkiz sətir və iki sətirdən ibarət bir şeir yazın",
 "Oyundakı insanların birgə qərarı ilə qruplardan birini öpün (ümumi bir qərar yoxdursa, /zar komandasından 1 -ə yaxın olan oyunçunu öpün).",
 "5 dəqiqə oyunda bir adama qul ol.", "Süpürgə və ya paspasla rəqs et və video çək".
 "Əsl sevginizin kim olduğunu elan edin", "Ağzınızı tərpətmədən əlifbanı əvvəldən sona qədər oxuyun, oxuyarkən video çəkin", "Ağlınıza ilk gələn sözü deyin",
 "Oyundakı oyunçulardan biri haqqında bir hekayə hazırla", "Əlifbanı 15 saniyədə yuxarıdan aşağıya oxu, oxuyarkən səs çıxart", "İt kimi hürərkən səs çıxart",
 "Başdan sona bir mahnı oxuyun, səssiz", "Görüşdüyünüz ən pis və ən yaxşı insanı təsvir edin.",
 "Bir dəqiqə əks cinsdən olan insan kimi gəzin.",
 "Məşhur restoranlardan birini çağırın və menyusunu öyrənərkən lağ edin.",
 "Keçmişinizə mesaj yazın və onu unuda bilməyəcəyinizi söyləyin.", "" Siz "sözünü 2 tur eşitdiyiniz zaman quş kimi səslənin.",
 "Telefonda hər kəsin brauzer tarixçəsini göstər"

D_LİST = [
	"Telefonunuza son zəng etdiyiniz şey nə idi?", "Biri qız yoldaşınızdan/sevgilinizdən ayrılmaq üçün sizə 1 milyon dollar təklif etsə, edərsinizmi?",
 "Bu qrupda ən çox kimdən xoşunuz gəlir və niyə?", "Heç sinifdə yüksək səslə ağlamısınızmı?",
 "Dərsdə nə vaxtsa yüksək səslə ağlamısanmı?", "Yerdən bir şey götürüb yedinmi?",
 "Bir gün əks cins olaraq oyansan, ilk növbədə nə edərsən?",
 "Hovuza işlətmisinizmi?", "Liftdə qaz buraxmısınızmı?",
 "Tualetdə oturanda ağla gələn şeylər nələrdir?", "Böyüyən xəyali bir dostun varmı?",
 "Ən pis vərdişiniz nədir?", "Burnunuzu seçirsinizmi?", "Hamamda mahnı oxuya bilirsinizmi?",
 "Heç işlətmisənmi?", "İctimai yerlərdə ən utanc verici anın nə idi?", "Heç güzgüdə özünlə danışmısanmı?",
 "Kimsə veb tarixçənizi görsəydi nədən utanardınız?", "Yuxuda danışırsınız?",
 "Gizli eşqiniz kimdir?", "Məndən nəyi bəyənmirsiniz?", "Hazırda hansı rəngli alt paltarı geyinirsiniz?",
 "Ən son göndərdiyiniz mətn nə idi?", "İnsanları yanan binadan xilas edirsinizsə və bu qrupdan bir nəfəri geridə qoymalı olsaydınız, kim olardı?",
 "Alt paltarınızı nə qədər tez -tez yuyursunuz?", "Qulaqcığın dadını heç hiss etmisinizmi?",
 "Nə vaxtsa başqasını qınadın və günahlandırdın?", "Heç tərini dadmısanmı?",
 "Bu otaqda kim ən pis adam olardı? Niyə?",
 "Yenidən doğulsaydınız, hansı əsrdə doğulmaq istərdiniz?", "Dediyiniz və ya etdiyiniz bir şeyi silmək üçün geriyə gedə bilsəydiniz, hansı il olardı?",
 "Sevgilin və ya sevgilin səni heç vaxt utandırıbmı?", "Birdən görünməz olsan nə edərdin?",
 "Hamamda qaldığın ən uzun müddət və niyə bu qədər uzun müddət qaldın?", "Mənə gördüyüm ən qəribə yuxudan danış.",
 "Duşda işəyirsənmi?", "Hələ etdiyin ən uşaqcasına iş nədir?", "Hansı uşaq filminə dəfələrlə baxa bilərsən?",
 "Pis ayaq qoxunuz varmı?", "Aptal ləqəbləriniz varmı?", "Telefonunuzda ən çox hansı vaxt keçirirsiniz?",
 "Bir oturuşda yediyiniz ən çox yemək nədir?", "Tək qalanda rəqs edirsinizmi?", "Qaranlıqdan qorxursunuz?",
 "Bütün günü evdə olsaydınız nə edərdiniz?", "Gündə neçə selfi çəkirsiniz?", "Sonuncu dəfə nə vaxt dişlərinizi fırçaladınız?",
 "Ən sevdiyiniz pijama nə kimi görünür?"
 "Bədəninizin hansı hissəsini sevirsiniz, nədən nifrət edirsiniz?", "Heç bitləriniz olubmu?",
 "Heç şalvarını kəsmisənmi?", "Tabağını yalayırsan?", "Sənin haqqında heç kimin bilmədiyi bir şey nədir?",
 "Heç boşqabınızı yaladınızmı?", "Dirsəyinizi yalaya bilərsinizmi?", "Buradakı hər kəsi yanan bir binadan qurtarmağa çalışsaydınız və kimisə geridə qoymalı olsaydınız, kimləri geridə qoyardınız?",
 "Telefonda axtardığınız son şey nə idi?", "Telefonunuzdan bir tətbiq silməli olsaydınız, hansını silərdiniz?", "Bir əlaqədə ən böyük qorxunuz nədir?",
 "Otaqdakı hər bir insan haqqında bir müsbət və bir mənfi şey söyləyin.", "Bəyənmədiyiniz pis vərdişləriniz varmı?",
 "Həyatınızda etdiyiniz ən çılğın şey nədir?", "Üç gün bir adada qalsaydınız, bu qrupdan kimləri seçərdiniz?",
 "Bu otaqdakı ən əsəbi adam kimdir?", "Bu qrupdan biriylə evlənməli olsaydınız, kim olardı?", "Ən uzun münasibətiniz nə qədərdi?",
 "İnstaqramda sizi bir məşhur izləsəydi, bu məşhurun ​​kim olmasını istərdiniz?", "İnstagramda 5 nəfəri silməli olsaydınız, kimləri silərdiniz?",
 "Neçə uşaq sahibi olmaq istərdiniz?", "Xəyallarınızdakı şəxsi təsvir edin.", "Messi yoxsa Ronaldo?", "Pes yoxsa FIFA?",
 "İlk işiniz nə idi?", "Kollec haqqında ən böyük qorxunuz nədir?", "Ən yaxın dostunuzun sizinlə eyni universitetə ​​getməsini istərdinizmi?",
 "İndiki sevgilinizin və ya sevgilinizin sizinlə eyni universitetə ​​getməsini istərdinizmi?", "Xəyalınızdakı iş nədir?",
 "Hələ bir dərs buraxmısınızmı?", "Heç aldatmısınızmı?", "Heç sinifdə yatmısınızmı?", "Kimin sinifdə yanında oturmaq istəməyəcəyini?",
 "Heç dərsə gecikmisinizmi?", "Müəllimin qarşısında etdiyiniz ən utanc verici şey nədir?", "Masanın altına saqqız qoymusunuzmu?",
 "Məktəbdə heç dava etdinizmi?", "Testdəki ən pis balınız hansı idi?", "Heç sinifdə yuxuya getmisinizmi?", "Heç saxlanılıbmı?",
 "Görünməz olsaydınız hansı sinfə girərdiniz?", "Hansı qrup ən pisdir?", "Bu qrupda sirr saxlamaqda ən çox kim çətinlik çəkir?",
 "Son dediyin yalan nə idi?", "İdman edirsənmi?", "Ömrünün sonuna qədər yalnız bir paltar geyə bilsəydin, nə rəng olardı?",
 "Sizcə, Türkiyənin təhsil sistemində edilməsi lazım olan ən əhəmiyyətli dəyişiklik nədir?", "Qaranlıqdan/yüksəklikdən qorxursunuz?",
 "1 -dən 10 -a qədər öz görünüşünüzü qiymətləndirin :)", "Etdiyiniz ən qanunsuz şey nə idi?", "İndi bəyənmədiyiniz insanla evlilik təklifiniz varsa və bu son evlilikdirsə sizə təklif, qəbul edərsinizmi? "
 "Mövcud əhvalınıza əsaslanaraq hansı filmə baxırsınız (aksiya/dram/elmi-fantastik/romantik komediya/tərcümeyi-hal/fantaziya)",
 "Ən çox itkin düşdüyünüz an hansı idi?", "Gələcəkdə uşağınız olsaydı hansı ad vermək istərdiniz?",
 "Tək boynuzlu və ya əjdaha sahibi olmaq istərdinizmi?", "Neçə qız yoldaşınız olub?",
 "sevdiyiniz mahnı?", "Etməməyiniz lazım olan bir şeyi edərkən tutuldunuzmu?", "Ən sevdiyiniz sənətçi kimdir?",
 "Qarşı cinslə bağlı ilk diqqət çəkdiyiniz şey nədir?", "Bu il həyatınızda nəyi dəyişməyi uyğun görürsünüz?",
 "Birinin telefonunda gördüyün ən qəribə şey nədir?", "Super qəhrəmanlar həqiqətən də olsaydı dünya necə olardı?",
 "Həyatın sizə öyrətdiyi ən əhəmiyyətli dərs nədir?", "Mədəniyyətimizin ən çox sevdiyiniz hissəsi nədir?", "Ailənizin tətbiq etdiyi ən qəribə ənənə nədir?",
 "Ailənizdən başqa, həyatınıza ən böyük təsir edən kimdir?", "Qadın/kişi olmağın ən pis və ən yaxşı tərəfi nədir?",
 "Beyninizi bir robotun içinə qoyub əbədi olaraq belə yaşaya bilsəydiniz, bunu edərdinizmi?", "Evinizdə yaşadığınız ən pis qonaq kim idi və nə oldu?",
 "İnsanlardan nə soruşmaqdan bezmisən?", "Ən qəribə qorxun nədir?", "Ən çox sevdiyin TV şou nədir?", "İndiyə qədər yaşadığın ən axmaq mübahisə nədir?",
 "Son dediyin yalan nədir?", "Tanışlıqda etdiyin ən utanc verici şey nə idi?",
 "Heç təsadüfən avtomobilinizlə bir şeyə və ya kiməsə vurdunuzmu (əgər varsa)?",
 "Bəyəndiyinizi düşündüyünüz, amma anlaşa bilməyəcəyiniz biri olubmu?", "Ən qəribə ləqəbiniz nədir?",
 "Fiziki olaraq ən ağrılı təcrübəniz nə idi?"
 "İctimai nəqliyyatda etdiyiniz ən çılğın şey nədir?", "Bir şüşədən bir cin çıxsaydı üç istəyiniz nə olardı?", "Dünyada kimisə Türkiyə prezidenti edə bilsəydiniz, kim edərdi? olmaq? ",
 "Başqasına dediyin ən qəddar söz nə idi?", "Birini öpərkən özünü pis hiss etmisənmi?", "Bunun heç bir nəticəsi olmayacağını bilsəydin nə edərdin?",
 "Bir güzgü qarşısında etdiyin ən çılğın şey nədir?", "Başqasına dediyin ən mənalı şey nədir?",
 "Dostlarınızla nə etməyi sevirsiniz, amma heç vaxt sevgilinizin gözü qarşısında etməzsiniz?", "Bu həyatda ən çox kimə qısqanırsınız?",
 "Ən sevdiyiniz pijamalar nəyə bənzəyir?", "Heç vaxt görüşməmək üçün xəstə kimi davranmısınızmı?", "Görüşdüyünüz ən yaşlı adam kimdir?",
 "Gündə neçə selfi çəkirsən?", "Gündə neçə selfi çəkirsən?", "Həftədə neçə dəfə eyni şalvar geyinirsən?",
 "Bu gün şansınız olsaydı, liseyinizin əziyyətini çəkərdinizmi?", "Bədəninizin hansı hissələrini qıdıqlayırsınız?",
 "Müxtəlif xurafatlarınız varmı? Əgər belədirsə, bunlar nədir?", "Hansı filmi sevdiyinizi etiraf etməkdən utanırsınız?", "Ən utanc verici özünə qulluq vərdişiniz nədir?", "Sonuncu dəfə nə vaxt və nə idi? nə vaxt üzr istədin? "," Şifahi dastanlar haqqında nə düşünürsən? ",
 "Ən çox utanc verici qoxular hardan qaynaqlanır?", "Qız yoldaşına danışmaq haqqında heç düşünmüsənmi?", "Qız yoldaşını heç kimlə aldatmısanmı?", "Boksçu və ya külot?", "Heç işəmisənmi? hovuzda yoxsa dənizdə? "," Saçlarınızı heç uzatmısınızmı? Nə vaxta qədər davam edəcəyini düşünürsünüz? "," Heç kimin bilməyəcəyinə zəmanət verilsəydi kimləri öldürərdin? "," Ən ucuz hədiyyə nədir? başqası üçün heç almısan? "
 "Vaxtınızın çox hissəsini hansı tətbiqə sərf edirsiniz?", "Avtobusda etdiyiniz ən qəribə şey nədir?", "Heç ictimai yerlərdə çılpaq olmusunuzmu?", "Gündə nə qədər dedi -qodu edirsiniz? "," Görüşmək istədiyin ən gənc adam neçə yaşında olardı? "Hələ heç bir yerdə burnunu çəkmirsənmi?",
 "Yaşınızla bağlı yalan danışmısınızmı?", "Telefonunuzdan bir tətbiq silməli olsaydınız, nə olardı?",
 "Gecə gec etdiyiniz ən utanc verici şey nədir?", "Duş almadan getdiyiniz ən uzun müddət nədir?", "Heç saxta şəxsiyyət vəsiqəsi istifadə etmisinizmi?", "İstədiyiniz ünlü kimdir? qırmızı xalça ilə gəzmək? "," Gizli eşqiniz kimdir? "
 ]
